#!/bin/bash

N1=`tac /opt/www/l2mh/services/dico.log | grep -m 1 -n 'start. servers' | sed -r 's/^([0-9]+).*/\1/g'`
tail -n $N1 /opt/www/l2mh/services/dico.log

echo ""
N2=`tac /opt/www/l2mh/services/drb.log | grep -m 1 -n 'Discord using gateway protocol' | sed -r 's/^([0-9]+).*/\1/g'`
tail -n $N2 /opt/www/l2mh/services/drb.log

echo ""
# ps aux | grep "dicobot" | grep -v "grep"
PID=`ps aux | grep '_dicobot' | grep -v grep | tr -s ' ' | cut -d ' ' -f 2`
ps -p $PID -o state,pid,vsz=MEMORY -o etime,atime -o args=ARGS
